'use strict';
// El original solo contenía Spotify. Para usar un MP3 autorizado, configura
// audioSrc:'assets/musica.mp3'. La reproducción local ya está preparada.
const CONFIG={audioSrc:'',eventDate:'2026-09-13T13:00:00-04:00',spotifyUri:'spotify:track:4OIp3u67j4xFlsTRlDmpKf'};
const $=id=>document.getElementById(id),openButton=$('open-button'),story=$('story'),audio=$('audio');
let opened=false,playing=false,wantsMusic=true,controller=null,spotifyReady=false,requestVersion=0,toastTimer;
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function setPlaying(value){playing=value;openButton.classList.toggle('playing',value);openButton.setAttribute('aria-label',value?'Pausar música':'Reproducir música');}
function setProgress(){const max=document.documentElement.scrollHeight-innerHeight;$('progress').style.width=(max>0?Math.min(100,Math.max(0,scrollY/max*100)):0)+'%';}addEventListener('scroll',setProgress,{passive:true});addEventListener('resize',setProgress);setProgress();
function addFallingBears(){if($('falling-sky').children.length)return;[8,29,65,86].forEach((left,i)=>{const img=document.createElement('img');img.className='falling-bear';img.src='assets/osito-globos.png';img.alt='';img.style.left=left+'%';img.style.animationDuration=(15+i*3)+'s';img.style.animationDelay=(-i*5)+'s';$('falling-sky').appendChild(img);});}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if('IntersectionObserver' in window&&!reduced){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));
function finishOpen(){document.body.classList.remove('locked');document.body.classList.add('opened');story.setAttribute('aria-hidden','false');openButton.classList.add('music-control');openButton.querySelector('.open-label').hidden=true;openButton.querySelector('.music-label').hidden=false;openButton.setAttribute('aria-label','Pausar música');addFallingBears();requestAnimationFrame(()=>story.scrollIntoView({behavior:reduced?'auto':'smooth'}));setTimeout(()=>document.querySelectorAll('.reveal').forEach(el=>{if(el.getBoundingClientRect().top<innerHeight*.9)el.classList.add('visible');}),700);}
async function localPlay(){const version=++requestVersion;audio.muted=false;try{await audio.play();if(version!==requestVersion||!wantsMusic){audio.pause();return;}setPlaying(!audio.paused&&!audio.muted);}catch(error){if(version!==requestVersion||!wantsMusic)return;toast(error.name==='NotAllowedError'?'Toca ♫ para permitir la música.':'La canción no pudo cargarse.');setPlaying(false);}}
function spotifyPlay(){if(controller&&spotifyReady){controller.play();setTimeout(()=>{if(wantsMusic&&!playing)toast('Spotify puede requerir permiso para reproducir la canción.');},2600);}}
function playMusic(){wantsMusic=true;if(CONFIG.audioSrc)localPlay();else spotifyPlay();}function pauseMusic(){wantsMusic=false;requestVersion++;audio.pause();if(controller)controller.pause();setPlaying(false);}
openButton.addEventListener('click',()=>{if(!opened){opened=true;playMusic();finishOpen();return;}if(playing)pauseMusic();else playMusic();});
audio.addEventListener('playing',()=>{if(!wantsMusic){audio.pause();return;}setPlaying(!audio.muted);});audio.addEventListener('pause',()=>setPlaying(false));audio.addEventListener('error',()=>{setPlaying(false);toast('No se pudo cargar la canción.');});
if(CONFIG.audioSrc){audio.src=CONFIG.audioSrc;audio.volume=.65;}else{window.onSpotifyIframeApiReady=api=>api.createController($('spotify-player'),{uri:CONFIG.spotifyUri,width:1,height:1},c=>{controller=c;c.addListener('ready',()=>{spotifyReady=true;if(opened&&wantsMusic)spotifyPlay();});c.addListener('playback_update',e=>{const on=!e.data.isPaused&&!e.data.isBuffering;if(on&&!wantsMusic){c.pause();return;}setPlaying(on);});});const script=document.createElement('script');script.src='https://open.spotify.com/embed/iframe-api/v1';script.async=true;document.head.appendChild(script);}
const eventDate=new Date(CONFIG.eventDate);function countdownValues(now){const q=Math.max(0,Math.floor((eventDate-now)/1000));return[Math.floor(q/86400),Math.floor(q%86400/3600),Math.floor(q%3600/60),q%60];}function tick(){countdownValues(new Date()).forEach((n,i)=>$(['days','hours','minutes','seconds'][i]).textContent=String(n).padStart(2,'0'));}tick();setInterval(tick,1000);
